/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Frame2038 from 'components/Frame2038/Frame2038';

const Group601 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1363px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Frame20381 = styled(Frame2038)(({ theme }) => ({
  position: `absolute`,
  left: `13px`,
  top: `0px`,
}));

const OrderCard1 = styled('img')({
  height: `66px`,
  width: `429px`,
  alignSelf: `stretch`,
  position: `absolute`,
  left: `956px`,
  top: `653px`,
});

const Frame80 = styled('img')({
  height: `117px`,
  width: `437px`,
  position: `absolute`,
  left: `953px`,
  top: `1210px`,
});

const Frame2039 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  left: `18px`,
  top: `229px`,
});

const DataTable = styled('img')({
  height: `317px`,
  width: `901px`,
  margin: `0px`,
});

const Image1 = styled('img')({
  height: `399px`,
  width: `422px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `953px`,
  top: `735px`,
});

const Frame36 = styled('img')({
  height: `307px`,
  width: `367px`,
  position: `absolute`,
  left: `5px`,
  top: `556px`,
});

const Group58 = styled('img')({
  height: `446px`,
  width: `940px`,
  position: `absolute`,
  left: `0px`,
  top: `917px`,
});

const Frame35 = styled('img')({
  height: `307px`,
  width: `365px`,
  position: `absolute`,
  left: `414px`,
  top: `556px`,
});

function Group60(props) {
  return (
    <Group601 className={props.className}>
      <Frame20381 />
      <OrderCard1
        src={`assets/images/Group60_Order_card.png`}
        loading="lazy"
        alt={'Order card'}
      />
      <Frame80
        src={`assets/images/Group60_Frame_80.png`}
        loading="lazy"
        alt={'Frame 80'}
      />
      <Frame2039>
        <DataTable
          src={`assets/images/Group60_Data_table.png`}
          loading="lazy"
          alt={'Data table'}
        />
      </Frame2039>
      <Image1
        src={`assets/images/Group60_image_1.png`}
        loading="lazy"
        alt={'image 1'}
      />
      <Frame36
        src={`assets/images/Group60_Frame_36.png`}
        loading="lazy"
        alt={'Frame 36'}
      />
      <Group58
        src={`assets/images/Group60_Group_58.png`}
        loading="lazy"
        alt={'Group 58'}
      />
      <Frame35
        src={`assets/images/Group60_Frame_35.png`}
        loading="lazy"
        alt={'Frame 35'}
      />
    </Group601>
  );
}

export default Group60;
